export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "quote"; text: string; author?: string }
  | { type: "callout"; variant: "tip" | "info" | "warning"; title: string; text: string }
  | { type: "divider" };

export type Article = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  readTime: string;
  date: string;
  dateISO: string;
  emoji: string;
  content: Block[];
};

export const CATEGORIES = [
  "Motywacja",
  "Poradnik",
  "Leczenie",
  "Zdrowie",
  "Relacje",
  "Techniki",
  "Historia",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_COLORS: Record<string, string> = {
  Motywacja: "bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300",
  Poradnik:  "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300",
  Leczenie:  "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300",
  Zdrowie:   "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300",
  Relacje:   "bg-pink-100 text-pink-800 dark:bg-pink-900/40 dark:text-pink-300",
  Techniki:  "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300",
  Historia:  "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300",
};

export const articles: Article[] = [
  {
    slug: "10-powodow-warto-rzucic-palenie",
    category: "Motywacja",
    title: "10 powodów, dla których warto rzucić palenie już dziś",
    excerpt: "Każda minuta bez papierosa to krok w stronę zdrowia. Poznaj konkretne zmiany, które zachodzą w Twoim ciele już po kilku godzinach.",
    readTime: "5 min",
    date: "12 cze 2026",
    dateISO: "2026-06-12",
    emoji: "💪",
    content: [
      { type: "p", text: "Przez lata mówiłem sobie: rzucę w poniedziałek. Potem przychodził poniedziałek. Wiesz, jak to się kończy. Ale pewnego dnia zacząłem zbierać powody – nie po to, żeby się zmusić, tylko żeby zobaczyć, czy w ogóle warto. Oto co zebrałem." },
      { type: "h2", text: "1. Po 20 minutach – już czujesz różnicę" },
      { type: "p", text: "Ciśnienie krwi spada. Tętno zwalnia. To nie metafora – to fizyka. Twoje serce dosłownie odetchnie z ulgą już po pierwszych minutach bez papierosa." },
      { type: "h2", text: "2. Po 8 godzinach – tlenek węgla znika" },
      { type: "p", text: "Tlenek węgla wypiera tlen z krwi. To dlatego palaczy często boli głowa i są zmęczeni. Po jednej nocy bez papierosa krew zaczyna transportować tlen tak, jak powinna." },
      { type: "h2", text: "3. Po 24 godzinach – ryzyko zawału spada" },
      { type: "p", text: "Jeden dzień. Jeden dzień i już zaczynasz zmniejszać ryzyko zawału serca. Brzmi jak reklama, ale to czysta medycyna." },
      { type: "h2", text: "4. Po 48 godzinach – wróci Ci smak i zapach" },
      { type: "p", text: "Pamiętam, jak po dwóch dniach zjadłem zwykłą pomarańczę i byłem w szoku. Zapomniałem, jak naprawdę smakuje jedzenie." },
      { type: "h2", text: "5. Po 2 tygodniach – łatwiej się oddycha" },
      { type: "p", text: "Rzęski w płucach zaczynają pracować. Odkrztuszanie, które przez lata traktowałem jako normę, przestaje być normą." },
      { type: "h2", text: "6. Po 3 miesiącach – płuca się naprawiają" },
      { type: "p", text: "Pojemność płuc rośnie o kilkanaście procent. Wejście po schodach na trzecie piętro przestaje być wyczynem." },
      { type: "h2", text: "7. Po roku – ryzyko chorób serca spada o połowę" },
      { type: "p", text: "Rok to nie tak dużo. A ryzyko zawału staje się o 50% niższe niż u osoby, która nadal pali. To liczba, którą warto sobie zapisać." },
      { type: "h2", text: "8. Po 5 latach – ryzyko udaru jak u niepalącego" },
      { type: "p", text: "Pięć lat i Twój mózg jest chroniony tak samo, jakbyś nigdy nie palił. Ciało ma niesamowitą zdolność do naprawy." },
      { type: "h2", text: "9. Zaoszczędzisz konkretne pieniądze" },
      { type: "p", text: "Paczka dziennie przez rok to grubo ponad 5000 złotych. Dwie paczki – bliżej 10 000. Możesz to zrobić z tymi pieniędzmi cokolwiek innego. Cokolwiek." },
      { type: "h2", text: "10. Przestaniesz się wstydzić" },
      { type: "p", text: "Nie mówiłem o tym głośno, ale był moment kiedy wychodziłem z kawiarni, żeby zapalić, i wracałem przesiąknięty dymem. Nie chciałem, żeby moje dzieci to czuły. To był mój nr 1. Każdy ma swoje." },
      { type: "callout", variant: "tip", title: "Zrób to teraz", text: "Napisz na kartce SWÓJ powód nr 1. Jeden. Trzymaj ją przy sobie przez pierwszy tydzień." },
    ],
  },
  {
    slug: "jak-radzic-sobie-z-glodem-nikotynowym",
    category: "Poradnik",
    title: "Jak radzić sobie z głodem nikotynowym?",
    excerpt: "Głód nikotynowy trwa zazwyczaj tylko 3–5 minut. Sprawdź, które techniki skutecznie pomagają go przetrwać bez sięgania po papierosa.",
    readTime: "7 min",
    date: "9 cze 2026",
    dateISO: "2026-06-09",
    emoji: "🧠",
    content: [
      { type: "p", text: "Nikt Ci nie powie, że głód nikotynowy jest przyjemny. Jest paskudny. Ale ma jedną słabość – trwa tylko 3 do 5 minut. Dosłownie. Jeśli przetrwasz te 5 minut, fala odpływa." },
      { type: "callout", variant: "info", title: "Ważna liczba", text: "Głód nikotynowy szczytuje po ok. 3 minutach i ustępuje. Większość ludzi nie wie, że to takie krótkie." },
      { type: "h2", text: "Technika 4-7-8 (działa naprawdę)" },
      { type: "p", text: "Wdech przez 4 sekundy, zatrzymaj powietrze na 7, wydech przez 8. Powtórz cztery razy. Zajmuje niecałą 2 minuty. Aktywuje układ nerwowy przywspółczulny – dosłownie wycisza panikę." },
      { type: "h2", text: "Zmień otoczenie od razu" },
      { type: "p", text: "Głód nikotynowy jest częściowo warunkowy. Kawa = papieros. Przerwa w pracy = papieros. Zmień cokolwiek – wstań, wyjdź do innego pomieszczenia, zadzwoń do kogoś. Przerwij ten automatyzm." },
      { type: "h2", text: "Miej coś pod ręką" },
      { type: "ul", items: [
        "Patyczek cynamonowy – do żucia, zastępuje gest",
        "Nasiona słonecznika bez łupinki",
        "Zimna woda – kilka łyków działa zaskakująco dobrze",
        "Guma do żucia bez cukru",
        "Wykałaczka – brzmi głupio, działa",
      ]},
      { type: "h2", text: "Aplikacja na telefon" },
      { type: "p", text: "Kiedy dopadnie Cię głód, otwórz aplikację do rzucania palenia i kliknij \"mam ochotę\". Większość z nich pokaże Ci licznik, ile pieniędzy już zaoszczędziłeś i jak długo nie palisz. To działa jak zimny prysznic motywacyjny." },
      { type: "h2", text: "A jeśli to nie działa?" },
      { type: "p", text: "Jeśli głód jest nie do wytrzymania i masz kilka takich fal dziennie – to może być sygnał, że warto sięgnąć po NRT (plastry, gumy, pastylki). Nie ma w tym wstydu. Uzależnienie jest fizyczne, nie tylko psychiczne." },
      { type: "callout", variant: "tip", title: "Moja technika awaryjna", text: "Kiedy naprawdę chciałem zapalić, robiłem 10 pompek. Do 10 byłem zbyt zmęczony, żeby myśleć o papierosie. Głupia technika. Działa." },
    ],
  },
  {
    slug: "zamienniki-nikotyny-co-wybrac",
    category: "Leczenie",
    title: "Zamienniki nikotyny – co wybrać?",
    excerpt: "Plastry, gumy, inhalatory, pastylki – porównujemy skuteczność wszystkich form NRT dostępnych bez recepty w polskich aptekach.",
    readTime: "9 min",
    date: "5 cze 2026",
    dateISO: "2026-06-05",
    emoji: "💊",
    content: [
      { type: "p", text: "NRT, czyli Nicotine Replacement Therapy – terapia zastępowania nikotyny. Brzmi medycznie. W skrócie: dajesz sobie nikotynę bez dymu, trucizn i smoły, żeby odzwyczaić ciało od papierosów. Bez wstydu. To po prostu leczenie." },
      { type: "h2", text: "Plastry – dla tych, co chcą spokoju" },
      { type: "p", text: "Naklejasz rano, zapominasz. Nikotyna wchłania się przez skórę przez całą dobę. Dobre, jeśli Twój głód jest równomierny przez cały dzień. Zły pomysł, jeśli kurysz tylko rano albo tylko przy stresie – wtedy dawka jest za mała lub za duża." },
      { type: "h2", text: "Gumy – dla tych, co potrzebują kontroli" },
      { type: "p", text: "Żujesz kiedy chcesz. Działają szybciej niż plastry – nikotyna wchłania się przez śluzówkę ust. Uwaga: żuć powoli i przygryzać, nie żuć jak zwykłą gumę. Technika się liczy." },
      { type: "h2", text: "Pastylki – jak gumy, ale wygodniejsze" },
      { type: "p", text: "Ssiesz powoli, nie żujesz. Świetne na sytuacje, kiedy nie możesz żuć (spotkanie, rozmowa). Dostępne w różnych smakach i dawkach." },
      { type: "h2", text: "Inhalatory – dla tych, co tęsknią za gestem" },
      { type: "p", text: "Mały plastikowy ustnik z wkładem nikotynowym. Trzymasz jak papierosa. Wciągasz jak papierosa. Zaspokaja zarówno fizyczne, jak i behawioralne uzależnienie. W Polsce trudniej dostępny, ale warto szukać." },
      { type: "h2", text: "Co wybrać?" },
      { type: "callout", variant: "info", title: "Prosta zasada", text: "Palisz ponad paczkę dziennie → zacznij od wyższej dawki (21 mg plastry, 4 mg gumy). Poniżej paczki → niższa dawka. W razie wątpliwości zapytaj w aptece – i tak opiszą Ci to lepiej niż ja." },
      { type: "p", text: "Badania pokazują, że kombinacja dwóch form NRT (np. plastry + gumy na głód) działa lepiej niż jedna. Mózg dostaje stabilną dawkę + szybką reakcję na kryzys." },
    ],
  },
  {
    slug: "mozg-po-rzuceniu-palenia",
    category: "Zdrowie",
    title: "Mózg po rzuceniu palenia – co się dzieje?",
    excerpt: "Nikotyna zmienia strukturę mózgu. Dobra wiadomość: te zmiany są odwracalne. Dowiedz się, kiedy i jak Twój mózg wraca do normy.",
    readTime: "8 min",
    date: "1 cze 2026",
    dateISO: "2026-06-01",
    emoji: "🧬",
    content: [
      { type: "p", text: "Nikotyna jest sprytna. Wchodzi do mózgu w 8 sekund – szybciej niż cokolwiek innego, co zażywasz doustnie. I od razu zaczyna tam rządzić." },
      { type: "h2", text: "Co robi nikotyna z mózgiem" },
      { type: "p", text: "Wiąże się z receptorami acetylocholiny i wywołuje wyrzut dopaminy. Czujesz się chwilowo lepiej, spokojniej, skupiasz się. Problem w tym, że mózg przestawia się na ten sztuczny dopamin. Zaczyna produkować mniej własnego." },
      { type: "p", text: "To dlatego kiedy nie palisz – czujesz się gorzej. Nie dlatego, że papieros naprawdę pomagał. Dlatego, że Twój mózg oduczył się działać bez niego." },
      { type: "h2", text: "Co się dzieje po rzuceniu" },
      { type: "ol", items: [
        "Pierwsze 72 godziny – najgorsze. Poziom dopaminy spada. Drażliwość, niepokój, problemy z koncentracją. To naprawdę boli.",
        "1–2 tygodnie – receptory zaczynają się normalizować. Stopniowo wraca naturalne \"neutralne\" samopoczucie.",
        "1–3 miesiące – produkcja dopaminy wraca do normy. Przestajesz potrzebować nikotyny żeby czuć się dobrze.",
        "6–12 miesięcy – większość zmian strukturalnych w mózgu wraca do stanu sprzed palenia.",
      ]},
      { type: "h2", text: "Czy głupiejesz na chwilę po rzuceniu?" },
      { type: "p", text: "Tak. Wielu palaczy w pierwszych tygodniach czuje się rozkojarzonych, mają problemy z koncentracją. To nie Ty – to Twój mózg kalibruje się na nowo. Mija." },
      { type: "callout", variant: "tip", title: "Pomóż mózgowi", text: "Ruch fizyczny przyspiesza produkcję dopaminy. 20 minut szybkiego marszu dziennie znacząco skraca czas powrotu do normy." },
    ],
  },
  {
    slug: "jak-przekonac-bliskich-do-rzucenia-palenia",
    category: "Relacje",
    title: "Jak przekonać bliskich do rzucenia palenia?",
    excerpt: "Namawianie na siłę rzadko działa. Eksperci podpowiadają, jak rozmawiać o paleniu tak, żeby bliska osoba sama podjęła decyzję.",
    readTime: "6 min",
    date: "28 maj 2026",
    dateISO: "2026-05-28",
    emoji: "❤️",
    content: [
      { type: "p", text: "Moja żona przez trzy lata prosiła mnie, żebym rzucił. Im bardziej prosiła, tym bardziej się broniłem. Paradoks? Nie. Tak działa ludzka psychologia." },
      { type: "h2", text: "Namawianie działa odwrotnie" },
      { type: "p", text: "Kiedy ktoś Ci mówi, żebyś coś zrobił – naturalnie chcesz udowodnić, że sam decydujesz. Zwłaszcza jeśli chodzi o uzależnienie, w którym jest dużo wstydu. Presja zamienia się w opór." },
      { type: "h2", text: "Co naprawdę działa" },
      { type: "p", text: "Zadawaj pytania, nie dawaj instrukcji. \"Jak się czujesz kiedy palisz?\" zamiast \"Powinieneś rzucić\". \"Co byś zyskał, gdybyś nie palił?\" zamiast \"Tracisz zdrowie\"." },
      { type: "p", text: "Psycholodzy nazywają to motywacyjnym wywiadem. Chodzi o to, żeby osoba sama wypowiedziała swoje argumenty. Słowa które sam/a mówisz mają sto razy więcej siły niż te, które słyszysz od kogoś innego." },
      { type: "h2", text: "Kiedy milczenie jest lepsze" },
      { type: "p", text: "Jeśli rozmawiałeś już kilka razy i nic się nie zmienia – odpuść na jakiś czas. Naprawdę. Nie znaczy to, że rezygnujesz. Znaczy, że dajesz przestrzeń. Często wtedy następuje przełom." },
      { type: "callout", variant: "warning", title: "Czego nie robić", text: "Nie chowaj papierosów, nie wyrzucaj ich bez pytania, nie komentuj przy innych. To upokarza i buduje mur, nie motywację." },
      { type: "h2", text: "Jeśli Cię kocha – zrobi to dla siebie, nie dla Ciebie" },
      { type: "p", text: "Paradoks rzucania palenia: najsilniejsi rzucają dla siebie. Twoja rola to być obok, wspierać – nie ciągnąć. Kiedy ta osoba będzie gotowa, miej pod ręką tę stronę." },
    ],
  },
  {
    slug: "cwiczenia-oddechowe-na-trudne-chwile",
    category: "Techniki",
    title: "Ćwiczenia oddechowe na trudne chwile",
    excerpt: "Kiedy dopada Cię stres i masz ochotę zapalić, te proste ćwiczenia oddechowe pomogą Ci odzyskać spokój w mniej niż 2 minuty.",
    readTime: "4 min",
    date: "24 maj 2026",
    dateISO: "2026-05-24",
    emoji: "🌬️",
    content: [
      { type: "p", text: "Palenie to w dużej mierze oddychanie. Wdech, wydech, pauza. Kiedy rzucasz – tracisz ten rytm. Na szczęście można go zastąpić czymś, co nie niszczy płuc." },
      { type: "h2", text: "Technika pudełka (Box Breathing)" },
      { type: "p", text: "Używają jej piloci wojskowi i ratownicy medyczni do opanowania stresu. Brzmi poważnie – jest prosta." },
      { type: "ol", items: [
        "Wdech przez nos – 4 sekundy",
        "Zatrzymaj oddech – 4 sekundy",
        "Wydech przez usta – 4 sekundy",
        "Zatrzymaj oddech – 4 sekundy",
        "Powtórz 4 razy",
      ]},
      { type: "h2", text: "Technika 4-7-8" },
      { type: "p", text: "Mocniejsza wersja dla trudniejszych momentów. Wdech przez 4, zatrzymaj przez 7, długi wydech przez 8. Ten długi wydech aktywuje nerw błędny – dosłownie sygnalizuje mózgowi \"spokój\"." },
      { type: "h2", text: "Oddech przeponowy" },
      { type: "p", text: "Połóż rękę na brzuchu. Wdech tak, żeby brzuch się uniósł, nie klatka piersiowa. Brzmi banalnie, ale 90% dorosłych oddycha płytko, klatkową. Przełączenie na brzuch zmienia wszystko." },
      { type: "callout", variant: "tip", title: "Kiedy ćwiczyć", text: "Nie czekaj na kryzys. Przez pierwsze dwa tygodnie ćwicz rano przez 3 minuty – wtedy kiedy kryzys przyjdzie, ciało już wie, co robić." },
    ],
  },
  {
    slug: "alkohol-i-papieros-jak-nie-wrocic",
    category: "Techniki",
    title: "Alkohol i papieros – jak nie wpaść w pułapkę?",
    excerpt: "Impreza, piwo, stary znajomy z paczką Marlboro… To jeden z najtrudniejszych momentów dla rzucających. Mam na to konkretny plan.",
    readTime: "6 min",
    date: "20 maj 2026",
    dateISO: "2026-05-20",
    emoji: "🍺",
    content: [
      { type: "p", text: "Statystyki są bezlitosne – wiele nawrotów zdarza się po alkoholu. Nie dlatego, że jesteś słaby. Dlatego, że alkohol i nikotyna są neurobiologicznie połączone. Obniżają tę samą barierę hamowania." },
      { type: "h2", text: "Dlaczego alkohol to tak trudny test" },
      { type: "p", text: "Alkohol zmniejsza aktywność kory przedczołowej – tej części mózgu, która mówi \"hej, nie rób tego\". Jednocześnie zapachy, muzyka, znajomi z papierosami aktywują stare nawyki. To podwójny cios." },
      { type: "h2", text: "Plan na wieczór z alkoholem" },
      { type: "ul", items: [
        "Powiedz znajomym przed przyjściem – jedno zdanie, żadnych wyjaśnień: \"Rzuciłem, więc nie proponuj mi papierosa.\"",
        "Miej plan ucieczki – jak będzie za ciężko, wyjdź. Nie musisz tłumaczyć.",
        "Ogranicz alkohol przez pierwsze 3 miesiące – nie musisz pić wody gazowanej przez rok, ale pierwsze tygodnie to czas, kiedy defenses są niskie.",
        "Trzymaj w kieszeni pastylkę nikotynową albo coś do żucia – na głód w trakcie imprezy.",
      ]},
      { type: "h2", text: "Jeśli zdarzy Ci się zapalić" },
      { type: "p", text: "Jeden papieros to nie koniec. Serio. Wiele osób traktuje \"wpadkę\" jako powód do rezygnacji. To błąd. Jeden papieros to potknięcie, nie upadek. Wróć na ścieżkę następnego ranka." },
      { type: "callout", variant: "warning", title: "Uwaga na myśl \"tylko jeden\"", text: "\"Tylko jeden\" to kłamstwo, które każdy palacz zna. Ale wiedzieć o kłamstwie i nie dać się mu wciągnąć to dwie różne rzeczy. Powiedz sobie: \"Wiem, że to kłamstwo\" i idź dalej." },
    ],
  },
  {
    slug: "pluca-po-rzuceniu-palenia-dzien-po-dniu",
    category: "Zdrowie",
    title: "Co dzieje się z Twoimi płucami – dzień po dniu",
    excerpt: "Po 20 minutach ciśnienie spada. Po 8 godzinach tlenek węgla znika z krwi. Po roku ryzyko zawału zmniejsza się o połowę. Sprawdź pełną listę.",
    readTime: "7 min",
    date: "15 maj 2026",
    dateISO: "2026-05-15",
    emoji: "🫁",
    content: [
      { type: "p", text: "Ciało ludzkie jest zdumiewające. Przez lata mu szkodziłem i przez lata się naprawiało – cichutko, bez fanfar, dzień po dniu. Oto co robi, kiedy dajesz mu szansę." },
      { type: "h2", text: "Pierwsze godziny" },
      { type: "ul", items: [
        "20 minut: ciśnienie krwi i tętno wracają do normy",
        "8 godzin: poziom tlenku węgla w krwi spada o połowę",
        "24 godziny: tlenek węgla całkowicie znika z organizmu",
        "48 godzin: receptory węchu i smaku zaczynają się regenerować",
      ]},
      { type: "h2", text: "Pierwszy tydzień i miesiąc" },
      { type: "ul", items: [
        "3 dni: nikotyna opuszcza organizm – szczyt objawów odstawiennych",
        "2–3 tygodnie: krążenie się poprawia, chodzenie po schodach przestaje być wyczynem",
        "1 miesiąc: rzęski w oskrzelach zaczynają działać – możesz więcej odkrztuszać, to dobry znak",
      ]},
      { type: "h2", text: "Rok i więcej" },
      { type: "ul", items: [
        "3–9 miesięcy: kaszel i duszności znacznie się zmniejszają",
        "1 rok: ryzyko choroby wieńcowej spada do połowy ryzyka palacza",
        "5 lat: ryzyko udaru mózgu jak u osoby niepalącej",
        "10 lat: ryzyko raka płuca spada o połowę",
        "15 lat: ryzyko chorób serca jak u osoby, która nigdy nie paliła",
      ]},
      { type: "callout", variant: "info", title: "Skąd te dane?", text: "To nie są marketingowe obietnice – to wyniki badań klinicznych zbieranych przez dziesięciolecia, m.in. przez American Heart Association i WHO." },
    ],
  },
  {
    slug: "rzucilem-po-20-latach",
    category: "Historia",
    title: "Rzuciłem po 20 latach i oto co się zmieniło",
    excerpt: "Przez dwie dekady byłem pewny, że palenie to część mnie. Dziś mam 3 lata bez papierosa. Piszę o tym, bo wiem, że możesz myśleć to samo.",
    readTime: "10 min",
    date: "10 maj 2026",
    dateISO: "2026-05-10",
    emoji: "🎉",
    content: [
      { type: "p", text: "Zapaliłem pierwszego papierosa w wieku 16 lat na podwórku za szkołą. Rzuciłem w wieku 39. Przez 23 lata byłem przekonany, że palenie to ja. Że bez papierosa nie ma Tomka." },
      { type: "h2", text: "Jak wyglądało te 20 lat" },
      { type: "p", text: "Rzucałem może 12, może 15 razy. Raz wytrwałem 8 miesięcy. Wróciłem przy pracy nad projektem, który mnie stresował. Mówiłem sobie: teraz potrzebuję, potem znowu rzucę. Potem nadchodziło kolejne \"teraz\"." },
      { type: "p", text: "Moja córka miała 4 lata, kiedy powiedziała, że nie chce, żebym przychodził po nią do przedszkola, bo śmierdzę. Brzmi brutalnie. Było brutalne. To był mój moment." },
      { type: "h2", text: "Jak rzuciłem tym razem" },
      { type: "p", text: "Nie zrobiłem nic wyjątkowego. Poszedłem do lekarza, dostałem wareniklinę (lek na receptę), ustawiłem datę i ją dotrzymałem. Żadnych magicznych rytuałów. Żadnego silnej woli. Tylko leczenie uzależnienia jak uzależnienia." },
      { type: "p", text: "Pierwsze trzy dni były naprawdę złe. Czwarty dzień był zły. Piąty – trochę lepszy. Po tygodniu pomyślałem: \"hej, właściwie mogę funkcjonować\"." },
      { type: "h2", text: "Co zmieniło się po roku" },
      { type: "ul", items: [
        "Śpię 7 godzin zamiast budzić się o 5 po papierosa",
        "Biegam 5 kilometrów – trzy lata temu zadyszka po przejściu na drugie piętro",
        "Moja córka już nie ucieka kiedy się przytulam",
        "Zaoszczędziłem ponad 18 000 zł (paczka dziennie × 3 lata)",
        "Nie wychodzę z restauracji na dymka w środku rozmowy",
      ]},
      { type: "h2", text: "Czy tęsknię za paleniem?" },
      { type: "p", text: "Szczerość? Przez pierwszy rok zdarzało się. Ale to było jak tęsknota za złą relacją – wiedziałem, że to nie jest prawdziwa tęsknota, tylko nawyk myślenia." },
      { type: "p", text: "Teraz, po 3 latach? Nie. Naprawdę nie." },
      { type: "h2", text: "Co chcę Ci powiedzieć" },
      { type: "p", text: "Jeśli palisz od lat i myślisz, że to \"część Ciebie\" – to największe kłamstwo, jakie powie Ci uzależnienie. Palenie to nie osobowość. To nałóg. Można go leczyć." },
      { type: "quote", text: "Nie byłem silny. Miałem dobrego lekarza, dobry lek i mały powód, który był ważniejszy niż moja wygoda.", author: "Tomek, czytelnik" },
    ],
  },
  {
    slug: "tycie-po-rzuceniu-palenia",
    category: "Zdrowie",
    title: "Tycie po rzuceniu palenia – mit czy rzeczywistość?",
    excerpt: "Tak, część osób przytywa. Ale średnio 2–4 kg. A palenie niszczy serce, płuca i naczynia o wiele bardziej niż te kilogramy. Liczby nie kłamią.",
    readTime: "6 min",
    date: "5 maj 2026",
    dateISO: "2026-05-05",
    emoji: "⚖️",
    content: [
      { type: "p", text: "Słyszę to regularnie: \"nie rzucę, bo przytyję\". Rozumiem ten strach. Ale powiedzmy sobie wprost – to jak bać się lekarstwa, bo może mieć skutek uboczny, podczas gdy choroba cię zabija." },
      { type: "h2", text: "Ile się przytywa? Naprawdę?" },
      { type: "p", text: "Średnia z badań to 4–5 kg w ciągu roku. Ale to średnia – połowa ludzi przytywa mniej lub wcale. Tylko kilka procent przytywa znacząco więcej." },
      { type: "h2", text: "Dlaczego to się dzieje" },
      { type: "ul", items: [
        "Nikotyna przyspiesza metabolizm – bez niej spowalnia",
        "Jedzenie znów smakuje – to bywa zaskakujące",
        "Gest \"sięgania po coś\" zostaje – ludzie jedzą zamiast palić",
        "Stres był regulowany papierosem – teraz szuka innego ujścia",
      ]},
      { type: "h2", text: "Co z tym zrobić" },
      { type: "p", text: "Nie siedź na diecie w pierwszym miesiącu. Serio. Masz już jedno trudne zadanie. Nie dokładaj drugiego. Zadbaj o to, żeby mieć pod ręką coś zdrowego do chrupania i żebyś się ruszał tyle ile możesz." },
      { type: "callout", variant: "info", title: "Proporcje mają znaczenie", text: "Palenie zwiększa ryzyko zawału serca o 200–300%. Nadwaga o 20–30%. Matematyka jest tu po Twojej stronie." },
    ],
  },
  {
    slug: "jak-przezyc-pierwszy-weekend-bez-papierosa",
    category: "Poradnik",
    title: "Jak przeżyć pierwszy weekend bez papierosa",
    excerpt: "Piątek wieczór, sobota rano, niedziela z kawą – to trzy najtrudniejsze momenty w pierwszym tygodniu. Napisałem plan na każdy z nich.",
    readTime: "8 min",
    date: "29 kwi 2026",
    dateISO: "2026-04-29",
    emoji: "📅",
    content: [
      { type: "p", text: "W tygodniu roboczym jest łatwiej – masz rytm, obowiązki, spotkania. Weekend to wolny czas. A wolny czas przez lata był papierosem." },
      { type: "h2", text: "Piątek wieczór" },
      { type: "p", text: "Najtrudniejszy moment: relaks po pracy. Ten papieros na kanapie z kawą albo piwem. Miej plan zamiennika – herbata, zimna woda z cytryną, coś do obgryzania. I powiedz komuś bliskim, żeby wiedzieli, że ten wieczór jest ważny." },
      { type: "h2", text: "Sobota rano" },
      { type: "p", text: "Poranny papieros był rytuałem. Zastąp go innym rytuałem. Nowym. Wyjdź na spacer zanim zaparzy się kawa – 15 minut. Idź do piekarni. Zadzwoń do znajomego. Mózg kocha rytuały i jest w stanie zamienić jeden na drugi." },
      { type: "h2", text: "Niedziela z nudą" },
      { type: "p", text: "Nuda to cichy wróg. Badania pokazują, że głód nikotynowy jest silniejszy podczas bezczynności. Zaplanuj coś na niedzielę – nawet coś małego. Kino, rower, sprzątanie przy muzyce. Cokolwiek." },
      { type: "callout", variant: "tip", title: "Plan na kryzys", text: "Zapisz na kartce trzy rzeczy, które zrobisz zamiast zapalić. Trzymaj kartkę przy sobie. Kiedy przyjdzie głód, sięgnij po nią, nie po papierosa." },
      { type: "h2", text: "Co po weekendzie" },
      { type: "p", text: "Jeśli przeżyłeś – jesteś twardszy niż myślisz. Naprawdę. Pierwszy weekend jest najtrudniejszy. Drugi jest łatwiejszy. Czwarty jest już całkiem normalny." },
    ],
  },
  {
    slug: "aplikacje-ktore-pomagaja-rzucic-palenie",
    category: "Poradnik",
    title: "Aplikacje, które naprawdę pomagają rzucić",
    excerpt: "Sprawdziłem 11 aplikacji do rzucania palenia. Większość to śmieć. Ale są 3, które robią różnicę. Tu je znajdziesz.",
    readTime: "5 min",
    date: "22 kwi 2026",
    dateISO: "2026-04-22",
    emoji: "📱",
    content: [
      { type: "p", text: "Przetestowałem aplikacje do rzucania palenia przez miesiąc. Część była naładowana reklamami, część \"motywacyjna\" w sposób, który irytuje. Ale trzy rzeczy wróciły do mojego telefonu." },
      { type: "h2", text: "Co powinna robić dobra aplikacja" },
      { type: "ul", items: [
        "Pokazywać, ile czasu nie palisz – w sekundach, minutach, godzinach",
        "Przeliczać to na pieniądze",
        "Dać przycisk \"mam głód\" z czymś pomocnym",
        "Nie zasypywać powiadomieniami",
      ]},
      { type: "h2", text: "Smoke Free" },
      { type: "p", text: "Mój faworyt. Czysta, prosta, bez zbędnych bajerów. Liczy czas, kasę i poprawę zdrowia. Animacje zdrowia są szczególnie motywujące – widać, jak konkretne organy się regenerują." },
      { type: "h2", text: "Kwit" },
      { type: "p", text: "Polska aplikacja, co już jest plusem. Społeczność aktywna, forum gdzie możesz napisać kiedy jest ciężko. Nie czujesz się sam w tej walce." },
      { type: "h2", text: "Quitnow!" },
      { type: "p", text: "Dobra dla tych, którzy lubią dane. Wykresy, liczby, statystyki. Jeśli motywuje Cię postęp w liczbach – to dla Ciebie." },
      { type: "callout", variant: "info", title: "Złota rada", text: "Nie szukaj idealnej aplikacji. Zainstaluj jedną, skonfiguruj i trzymaj się jej przez miesiąc. Zmienianie aplikacji to odwlekanie." },
    ],
  },
  {
    slug: "e-papierosy-czy-pomagaja-rzucic",
    category: "Leczenie",
    title: "Czy e-papierosy naprawdę pomagają rzucić?",
    excerpt: "Badania mówią jedno, reklamy mówią drugie. Zebrałem aktualne dowody naukowe i napisałem co z nich wynika – bez owijania w bawełnę.",
    readTime: "9 min",
    date: "15 kwi 2026",
    dateISO: "2026-04-15",
    emoji: "🔬",
    content: [
      { type: "p", text: "E-papierosy są wszędzie i każdy ma na nie opinię. Ja mam opinię opartą na badaniach – nie na reklamach e-papierosów ani na straszeniu ze strony moralizatorów." },
      { type: "h2", text: "Co mówią badania" },
      { type: "p", text: "Przegląd Cochrane'a z 2023 roku (najwyższy poziom dowodów naukowych) mówi jasno: e-papierosy pomagają rzucić palenie skuteczniej niż NRT i placebo. Ale jest kilka zastrzeżeń." },
      { type: "h2", text: "Te \"ale\" są ważne" },
      { type: "ul", items: [
        "Większość badanych nie rzuciła całkowicie – przeszła z papierosów na e-papierosy",
        "Długoterminowe skutki e-papierosów nie są znane (to nowy produkt)",
        "Rynek e-papierosów jest mało regulowany – nie wiesz, co wdychasz",
        "E-papierosy utrzymują uzależnienie od nikotyny, nie leczą go",
      ]},
      { type: "h2", text: "Moje zdanie" },
      { type: "p", text: "Jeśli masz wybór między e-papierosem a zwykłym papierosem – e-papieros jest prawdopodobnie mniej szkodliwy. Ale celem powinno być całkowite rzucenie nikotyny, nie zamiana jednego nałogu na inny." },
      { type: "callout", variant: "info", title: "Rekomendacja lekarzy", text: "Większość towarzystw pulmonologicznych mówi: e-papieros to narzędzie pomostowe, nie docelowe. Używaj go żeby rzucić papierosy – potem rzuć e-papierosy." },
    ],
  },
  {
    slug: "kiedy-mija-glod-nikotynowy",
    category: "Zdrowie",
    title: "Kiedy mija głód? Prawdziwe liczby, nie obietnice",
    excerpt: "Nie powiem Ci, że po tygodniu jest idealnie. Powiem Ci, co naprawdę czułem w 1., 3., 7. i 30. dniu. I kiedy naprawdę zrobiło się łatwiej.",
    readTime: "7 min",
    date: "8 kwi 2026",
    dateISO: "2026-04-08",
    emoji: "⏰",
    content: [
      { type: "p", text: "Wszędzie czytasz \"po 3 tygodniach jest lepiej\". To prawda. Ale nie mówi Ci nikt, co konkretnie dzieje się w środku. Oto mój dziennik." },
      { type: "h2", text: "Dzień 1–3: najgorszy okres" },
      { type: "p", text: "Fizyczny głód jest najsilniejszy. Nikotyna opuszcza ciało po 72 godzinach. To czas drażliwości, trudności ze skupieniem, bezsenności. Niektórzy mają bóle głowy. To normalne – to odtrucie." },
      { type: "h2", text: "Tydzień 1–2: psychiczne uzależnienie wychodzi na wierzch" },
      { type: "p", text: "Fizyczne objawy maleją, ale zaczyna być widoczne, ile rytuałów miało papierosa w tle. Kawa, spotkania ze znajomymi, stres. Głód wraca przy konkretnych wyzwalaczach." },
      { type: "h2", text: "Miesiąc 1–3: nowa normalność" },
      { type: "p", text: "Większość ludzi mówi, że po miesiącu głód przychodzi rzadziej. Zamiast co godzinę – kilka razy dziennie. Zamiast trwać 5 minut – minutę albo dwie." },
      { type: "h2", text: "Po 3 miesiącach" },
      { type: "p", text: "Tu dzieje się coś ciekawego. Większość receptorów nikotynowych w mózgu wróciła do normy. Głód jest rzadki i słabszy. Zdarzają się jeszcze \"fale\" – zazwyczaj przy konkretnym zapachu albo silnym stresie. Ale naprawdę maleją." },
      { type: "callout", variant: "tip", title: "Moja obserwacja", text: "Szczyty i dołki głodu są bardziej przewidywalne niż myślisz. Zacznij je notować. Zobaczysz wzorzec – i łatwiej go pokonać kiedy wiesz, kiedy uderzy." },
    ],
  },
  {
    slug: "co-powiedziec-znajomym-ktorzy-nadal-pala",
    category: "Relacje",
    title: "Co powiedzieć znajomym, którzy nadal palą",
    excerpt: "Nagle stajesz się tym, który nie pali. Znajomi zapraszają na dymka. Szef proponuje przerwę przy papierosie. Mam gotowe odpowiedzi na te sytuacje.",
    readTime: "5 min",
    date: "1 kwi 2026",
    dateISO: "2026-04-01",
    emoji: "🗣️",
    content: [
      { type: "p", text: "Kiedy rzucisz palenie, zmienia się Twoja rola w grupie. Już nie wychodzisz razem na dymka. Możliwe, że ktoś się obraża. Możliwe, że zaczną Cię namawiać \"tylko jednego\". Miej gotowe zdania." },
      { type: "h2", text: "Kiedy zapraszają na papierosa" },
      { type: "p", text: "Krótko i bez przeprosin: \"Nie, dzięki, rzuciłem\". Koniec. Nie musisz tłumaczyć, przekonywać ani dawać wykładu o zdrowiu. Jeden spokojny komunikat wystarczy." },
      { type: "h2", text: "Kiedy namawiają \"tylko jednego\"" },
      { type: "p", text: "\"Dzięki, ale wolę nie ryzykować\". Albo po prostu: \"Wiem, o co chodzi, nie dzisiaj\". Nie musisz wchodzić w dyskusję o tym, dlaczego jeden nie zaszkodzi. Wiesz, że zaszkodzi Twojemu planowi." },
      { type: "h2", text: "Kiedy ktoś się obraża, że \"zmieniłeś się\"" },
      { type: "p", text: "To się zdarza. Szczególnie kiedy byłeś \"tym z grupy, który pali\". Możesz powiedzieć szczerze: \"Tak, zmieniłem się. To dobra zmiana dla mnie\". Jeśli komuś to nie odpowiada – to jego problem, nie Twój." },
      { type: "callout", variant: "tip", title: "Złota zasada", text: "Nie musisz nikogo nawracać. Nie tłumacz się za bardzo. Im mniej robisz z tego produkcji, tym mniej presji od otoczenia." },
      { type: "h2", text: "A co z przerwami w pracy?" },
      { type: "p", text: "Przerwy przy papierosie to też networking. Nie musisz ich rezygnować – po prostu wyjdź razem ze znajomymi z kawą. Większość ludzi nie ma nic przeciwko. A Ty nie czujesz się wykluczony." },
    ],
  },
];
